package main

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTrimPeptides(t *testing.T) {
	signalPeptides := map[string]int{
		"A0A024R1R8": 15,
		"Q9BUL8":     13,
	}
	uniprotdatabase := &database{
		"A0A024R1R8": &databaseEntry{
			Header:   ">tr|A0A024R1R8|A0A024R1R8_HUMAN HCG2014768, isoform CRA_a OS=Homo sapiens (Human) OX=9606 GN=ENSG00000225528 PE=4 SV=1",
			Sequence: "MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAKVVGKGPLATGGIKKSGKK",
		},
		"A0A075B6H5": &databaseEntry{
			Header: ">tr|A0A075B6H5|A0A075B6H5_HUMAN Ig-like domain-containing protein OS=Homo sapiens (Human) OX=9606 GN=TRBV20OR9-2 PE=4 SV=1",
			Sequence: "METVVTTLPREGGVGPSRKMLLLLLLLGPGSGLSAVVSQHPSRVICKSGTSVNIECRSLD" +
				"FQATTMFWYRQLRKQSLMLMATSNEGSEVTYEQGVKKDKFPINHPNLTFSALTVTSAHPE" +
				"DSSFYICSAR",
		},
		"Q9BUL8": &databaseEntry{
			Header: ">sp|Q9BUL8|PDC10_HUMAN Programmed cell death protein 10 OS=Homo sapiens (Human) OX=9606 GN=PDCD10 PE=1 SV=1",
			Sequence: "MRMTMEEMKNEAETTSMVSMPLYAVMYPVFNELERVNLSAAQTLRAAFIKAEKENPGLTQ" +
				"DIIMKILEKKSVEVNFTESLLRMAADDVEEYMIERPEPEFQDLNEKARALKQILSKIPDE" +
				"INDRVRFLQTIKDIASAIKELLDTVNNVFKKYQYQNRRALEHQKKEFVKYSKSFSDTLKT" +
				"YFKDGKAINVFVSANRLIHQTNLILQTFKTVA",
		},
	}

	expected := &database{
		"A0A024R1R8": &databaseEntry{
			Header:   ">tr|A0A024R1R8|A0A024R1R8_HUMAN HCG2014768, isoform CRA_a OS=Homo sapiens (Human) OX=9606 GN=ENSG00000225528 PE=4 SV=1",
			Sequence: "KKQAKEMDEEEKAFKQKQKEEQKKLEVLKAKVVGKGPLATGGIKKSGKK",
		},
		"A0A075B6H5": &databaseEntry{
			Header: ">tr|A0A075B6H5|A0A075B6H5_HUMAN Ig-like domain-containing protein OS=Homo sapiens (Human) OX=9606 GN=TRBV20OR9-2 PE=4 SV=1",
			Sequence: "METVVTTLPREGGVGPSRKMLLLLLLLGPGSGLSAVVSQHPSRVICKSGTSVNIECRSLD" +
				"FQATTMFWYRQLRKQSLMLMATSNEGSEVTYEQGVKKDKFPINHPNLTFSALTVTSAHPE" +
				"DSSFYICSAR",
		},
		"Q9BUL8": &databaseEntry{
			Header: ">sp|Q9BUL8|PDC10_HUMAN Programmed cell death protein 10 OS=Homo sapiens (Human) OX=9606 GN=PDCD10 PE=1 SV=1",
			Sequence: "TTSMVSMPLYAVMYPVFNELERVNLSAAQTLRAAFIKAEKENPGLTQ" +
				"DIIMKILEKKSVEVNFTESLLRMAADDVEEYMIERPEPEFQDLNEKARALKQILSKIPDE" +
				"INDRVRFLQTIKDIASAIKELLDTVNNVFKKYQYQNRRALEHQKKEFVKYSKSFSDTLKT" +
				"YFKDGKAINVFVSANRLIHQTNLILQTFKTVA",
		},
	}
	trimPeptides(signalPeptides, uniprotdatabase)
	assert.Equal(t, expected, uniprotdatabase, "should trim signal peptides")
}
